require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.7
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5